(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition main (_ : unit) : (unit*unit) :=
  let num := 9 in
  (failure ("(FunctionalizeLoops) something is not implemented yet.This is discussed in issue https://github.com/hacspec/hax/issues/405.
Please upvote or comment this issue if you see this error message.
Loop without mutation"%string) ("{
 loop {
 (if core::cmp::f_ge(num, 10) {
 Tuple0
 } else {
 {
 let hoist1: tuple0 = {
 rust_primitives::hax::failure(
 "(CfIntoMonads) something is not implemented yet.This is discussed in issue http..."%string),tt).
