(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Record t_Version : Type :=
  {
    f_major : t_usize;
    f_minor : t_usize;
    f_patch : t_usize;
  }.
Arguments t_Version:clear implicits.
Arguments t_Version.
Arguments Build_t_Version.
#[export] Instance settable_t_Version : Settable _ :=
  settable! (@Build_t_Version) <f_major; f_minor; f_patch>.















Definition impl_Version__new (major : t_usize) (minor : t_usize) (patch : t_usize) : t_Version :=
  Build_t_Version (major, minor, patch).

Definition main (_ : unit) : unit :=
  let version_3_2_1_ := impl_Version__new (3) (2) (1) in
  let version_3_3_0_ := impl_Version__new (3) (3) (0) in
  let _ := e_print (impl_2__new_v1 ([""%string; " < "%string; " = "%string; "
"%string]) ([impl_1__new_debug (version_3_2_1_); impl_1__new_debug (version_3_3_0_); impl_1__new_display (f_lt (version_3_2_1_) (version_3_3_0_))])) in
  let _ := tt in
  tt.
