(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition wide_function (_ : unit) : unit :=
  let _ := tt in
  tt.

Definition long_function (_ : unit) : unit :=
  tt.

Definition far_function (_ : unit) : unit :=
  tt.

Definition main (_ : unit) : unit :=
  let _ := wide_function (tt) in
  let _ := long_function (tt) in
  let _ := far_function (tt) in
  tt.
