(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition explicit_unit (_ : unit) : unit :=
  let closure := fun _ =>
    let _ := tt in
    tt in
  let _ := drop (closure) in
  tt.

Definition implicit_unit (_ : unit) : unit :=
  let closure := fun _ =>
    let _ := tt in
    tt in
  let _ := drop (closure) in
  tt.

Definition main (_ : unit) : unit :=
  let _ := explicit_unit (tt) in
  let _ := implicit_unit (tt) in
  tt.
