(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition v_NO_BLOCK : unit -> unit :=
  fun _ =>
    let _ := e_print (impl_2__new_const (["hello
"%string])) in
    tt.

Definition v_WITH_BLOCK : unit -> unit :=
  fun _ =>
    let _ := e_print (impl_2__new_const (["hello
"%string])) in
    let _ := tt in
    tt.

Definition main (_ : unit) : unit :=
  let _ := v_NO_BLOCK (tt) in
  let _ := v_WITH_BLOCK (tt) in
  tt.
