(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition unused_pub_fn_not_in_library (_ : unit) : unit :=
  let is_true := f_eq (f_len (args (tt))) (1) in
  let countdown := 0 in
  if
    is_true
  then
    let countdown := 10 in
    tt
  else
    tt.

Definition unused_fn (_ : unit) : unit :=
  let is_true := f_eq (f_len (args (tt))) (1) in
  let countdown := 0 in
  if
    is_true
  then
    let countdown := 10 in
    tt
  else
    tt.

Definition main (_ : unit) : unit :=
  let is_true := f_eq (f_len (args (tt))) (1) in
  let countdown := 0 in
  if
    is_true
  then
    let countdown := 10 in
    tt
  else
    tt.
