(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Record t_MyStruct : Type :=
  {
  }.
Arguments t_MyStruct:clear implicits.
Arguments t_MyStruct.
Arguments Build_t_MyStruct.
#[export] Instance settable_t_MyStruct : Settable _ :=
  settable! (@Build_t_MyStruct) <>.

Definition impl_MyStruct__off_inherit (_ : unit) : unit :=
  tt.

Definition impl_MyStruct__off_on (_ : unit) : unit :=
  tt.

Definition impl_MyStruct__off_off (_ : unit) : unit :=
  tt.

Definition impl_MyStruct__on_inherit (_ : unit) : unit :=
  tt.

Definition impl_MyStruct__on_on (_ : unit) : unit :=
  tt.

Definition impl_MyStruct__on_off (_ : unit) : unit :=
  tt.

Class t_MyTrait `{v_Self : Type} : Type :=
  {
    f_method : unit -> unit;
  }.
Arguments t_MyTrait:clear implicits.
Arguments t_MyTrait (_).

Instance t_MyTrait_739506156 : t_MyTrait ((t_MyStruct)) :=
  {
    t_MyTrait_f_method := fun (_ : unit) =>
      tt;
  }.

Definition main (_ : unit) : unit :=
  tt.
