(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

(* NotImplementedYet *)

Definition affected_function (_ : unit) : unit -> unit :=
  fun _ =>
    tt.

Definition main (_ : unit) : unit :=
  let _ := f_call (affected_function (tt)) (tt) in
  tt.
