(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition accept_7_conditions (bool_arr : t_Array (bool) (7)) : unit :=
  failure ("(AST import) something is not implemented yet.This is discussed in issue https://github.com/hacspec/hax/issues/804.
Please upvote or comment this issue if you see this error message.
Pat:Array"%string) (""%string).

Definition main (_ : unit) : unit :=
  let _ := accept_7_conditions (repeat (false) (7)) in
  let _ := accept_7_conditions (repeat (true) (7)) in
  tt.
