(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Record t_Firework : Type :=
  {
    f_strength : t_i32;
  }.
Arguments t_Firework:clear implicits.
Arguments t_Firework.
Arguments Build_t_Firework.
#[export] Instance settable_t_Firework : Settable _ :=
  settable! (@Build_t_Firework) <f_strength>.

Instance t_Drop_893648624 : t_Drop ((t_Firework)) :=
  {
    t_Drop_f_drop := fun (self : t_Firework) =>
      let _ := e_print (impl_2__new_v1 (["BOOM times "%string; "!!!
"%string]) ([impl_1__new_display (f_strength self)])) in
      let _ := tt in
      self;
  }.

Definition main (_ : unit) : t_Result ((unit)) ((t_u8)) :=
  run (let e_firecracker := Build_t_Firework (1) in
  let e_tnt := Build_t_Firework (100) in
  let _ := if
    true
  then
    let _ := e_print (impl_2__new_const (["Exiting with error...
"%string])) in
    let _ := tt in
    let hoist1 := ControlFlow_Break (Result_Err (1)) in
    ControlFlow_Continue (never_to_any (hoist1))
  else
    ControlFlow_Continue (tt) in
  ControlFlow_Continue (let _ := Build_t_Firework (1000) in
  Result_Ok (tt))).
