(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition do_stuff (_ : unit) : unit :=
  tt.

Definition dense_a__dense_b__dense_c (_ : unit) : unit :=
  let _ := do_stuff (tt) in
  tt.

Definition dense_a__dense_b (_ : unit) : unit :=
  let _ := dense_a__dense_b__dense_c (tt) in
  let _ := dense_a__dense_b__dense_c (tt) in
  tt.

Definition dense_a (_ : unit) : unit :=
  let _ := dense_a__dense_b (tt) in
  let _ := dense_a__dense_b (tt) in
  tt.

Definition sparse_a__sparse_b__sparse_c__sparse_d__sparse_e (_ : unit) : unit :=
  let _ := do_stuff (tt) in
  tt.

Definition sparse_a__sparse_b__sparse_c__sparse_d (_ : unit) : unit :=
  let _ := sparse_a__sparse_b__sparse_c__sparse_d__sparse_e (tt) in
  let _ := sparse_a__sparse_b__sparse_c__sparse_d__sparse_e (tt) in
  tt.

Definition sparse_a__sparse_b__sparse_c (_ : unit) : unit :=
  let _ := sparse_a__sparse_b__sparse_c__sparse_d (tt) in
  let _ := sparse_a__sparse_b__sparse_c__sparse_d (tt) in
  tt.

Definition sparse_a__sparse_b (_ : unit) : unit :=
  let _ := sparse_a__sparse_b__sparse_c (tt) in
  let _ := sparse_a__sparse_b__sparse_c (tt) in
  tt.

Definition sparse_a (_ : unit) : unit :=
  let _ := sparse_a__sparse_b (tt) in
  let _ := sparse_a__sparse_b (tt) in
  tt.

Definition main (_ : unit) : unit :=
  let _ := dense_a (tt) in
  let _ := sparse_a (tt) in
  tt.
