(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition dead (_ : unit) : t_u32 :=
  42.

Definition live `{v_B : bool} (_ : unit) : t_u32 :=
  if
    v_B
  then
    dead (tt)
  else
    0.

Definition main (_ : unit) : unit :=
  let _ := e_print (impl_2__new_v1 ([""%string; "
"%string]) ([impl_1__new_display (live (tt))])) in
  let _ := tt in
  let f := fun x =>
    let _ := if
      true
    then
      let _ := assert (x) in
      tt
    else
      tt in
    tt in
  let _ := f_call (f) ((false)) in
  tt.
