(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

From Coverage Require Import Core_Hint (t_black_box).
Export Core_Hint (t_black_box).

Definition assign_and (a : bool) (b : bool) : unit :=
  let x := andb (a) (b) in
  let _ := black_box (x) in
  tt.

Definition assign_or (a : bool) (b : bool) : unit :=
  let x := orb (a) (b) in
  let _ := black_box (x) in
  tt.

Definition assign_3_ (a : bool) (b : bool) (c : bool) : unit :=
  let x := orb (a) (andb (b) (c)) in
  let _ := black_box (x) in
  tt.

Definition assign_3_bis (a : bool) (b : bool) (c : bool) : unit :=
  let x := orb (andb (a) (b)) (c) in
  let _ := black_box (x) in
  tt.

Definition right_comb_tree (a : bool) (b : bool) (c : bool) (d : bool) (e : bool) : unit :=
  let x := andb (a) (andb (b) (andb (c) (andb (d) (e)))) in
  let _ := black_box (x) in
  tt.

Definition foo (a : bool) : bool :=
  black_box (a).

Definition func_call (a : bool) (b : bool) : unit :=
  let _ := foo (andb (a) (b)) in
  tt.

Definition main (_ : unit) : unit :=
  let _ := assign_and (true) (false) in
  let _ := assign_and (true) (true) in
  let _ := assign_and (false) (false) in
  let _ := assign_or (true) (false) in
  let _ := assign_or (true) (true) in
  let _ := assign_or (false) (false) in
  let _ := assign_3_ (true) (false) (false) in
  let _ := assign_3_ (true) (true) (false) in
  let _ := assign_3_ (false) (false) (true) in
  let _ := assign_3_ (false) (true) (true) in
  let _ := assign_3_bis (true) (false) (false) in
  let _ := assign_3_bis (true) (true) (false) in
  let _ := assign_3_bis (false) (false) (true) in
  let _ := assign_3_bis (false) (true) (true) in
  let _ := right_comb_tree (false) (false) (false) (true) (true) in
  let _ := right_comb_tree (true) (false) (false) (true) (true) in
  let _ := right_comb_tree (true) (true) (true) (true) (true) in
  let _ := func_call (true) (false) in
  let _ := func_call (true) (true) in
  let _ := func_call (false) (false) in
  tt.
