(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition generic_fn `{v_T : Type} `{t_Sized (v_T)} (cond : bool) : unit :=
  if
    cond
  then
    let _ := e_print (impl_2__new_v1 ([""%string; "
"%string]) ([impl_1__new_display (type_name (tt))])) in
    let _ := tt in
    tt
  else
    tt.

Definition other_fn (_ : unit) : unit :=
  tt.

Definition main (_ : unit) : unit :=
  let cond := f_gt (f_len (args (tt))) (1) in
  let _ := generic_fn (cond) in
  let _ := generic_fn (f_not (cond)) in
  let _ := if
    black_box (false)
  then
    let _ := generic_fn (cond) in
    tt
  else
    tt in
  let _ := generic_fn (cond) in
  let _ := other_fn (tt) in
  tt.
