(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition main (_ : unit) : unit :=
  let _ := assert (true) in
  let _ := assert (f_not (false)) in
  let _ := assert (f_not (f_not (true))) in
  let _ := assert (f_not (f_not (f_not (false)))) in
  tt.
