(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition a (_ : unit) : t_Option ((t_i32)) :=
  let _ := Option_Some (7) in
  Option_Some (0).

Definition b (_ : unit) : t_Option ((t_i32)) :=
  run (let _ := Option_Some (7) in
  Option_Some (Option_Some (0))).

Definition c (_ : unit) : t_Option ((t_i32)) :=
  run (let _ := Option_Some (7) in
  Option_Some (Option_Some (0))).

Definition d (_ : unit) : t_Option ((t_i32)) :=
  run (let _ : unit := tt in
  let _ := Option_Some (7) in
  Option_Some (Option_Some (0))).

Definition main (_ : unit) : unit :=
  let _ := a (tt) in
  let _ := b (tt) in
  let _ := c (tt) in
  let _ := d (tt) in
  tt.
