(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition main (_ : unit) : t_Result ((unit)) ((t_u8)) :=
  let countdown := 10 in
  let countdown := failure ("(FunctionalizeLoops) something is not implemented yet.This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Unhandled loop kind"%string) ("{
 (loop {
 |countdown| {
 (if core::cmp::f_gt(countdown, 0) {
 {
 #[note(
 "rhs.typ=core::ops::control_flow::t_ControlFlow<core::result::t_Result<tuple0, int>, tuple0>"
 )]
 #[monadic_let(MException<..."%string) in
  Result_Ok (tt).
