(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition inlined_instance (a : bool) (b : bool) : bool :=
  andb (a) (b).

Definition main (_ : unit) : unit :=
  let _ := inlined_instance (true) (false) in
  let _ := inlined_instance (false) (true) in
  let _ := inlined_instance (true) (true) in
  tt.
