(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

TODO: please implement the method `item'_HaxError`

Record t_S : Type :=
  {
  }.
Arguments t_S:clear implicits.
Arguments t_S.
Arguments Build_t_S.
#[export] Instance settable_t_S : Settable _ :=
  settable! (@Build_t_S) <>.

Instance t_T_128246705 : t_T ((t_S)) :=
  {
    t_T_f_f := fun (self : t_S) =>
      let _ := e_print (impl_2__new_const (["impl S
"%string])) in
      let _ := tt in
      tt;
  }.

Definition main (_ : unit) : unit :=
  let _ := f_f (Build_t_S) in
  tt.
