(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Record t_Foo : Type :=
  {
    0 : t_u32;
  }.
Arguments t_Foo:clear implicits.
Arguments t_Foo.
Arguments Build_t_Foo.
#[export] Instance settable_t_Foo : Settable _ :=
  settable! (@Build_t_Foo) <0>.









Definition main (_ : unit) : unit :=
  let bar := Build_t_Foo (1) in
  let _ := match (bar,Build_t_Foo (1)) with
  | (left_val,right_val) =>
    assert (f_eq (left_val) (right_val))
  end in
  let baz := Build_t_Foo (0) in
  let _ := match (baz,Build_t_Foo (1)) with
  | (left_val,right_val) =>
    assert (f_not (f_eq (left_val) (right_val)))
  end in
  let _ := e_print (impl_2__new_v1 ([""%string; "
"%string]) ([impl_1__new_debug (Build_t_Foo (1))])) in
  let _ := tt in
  let _ := e_print (impl_2__new_v1 ([""%string; "
"%string]) ([impl_1__new_debug (bar)])) in
  let _ := tt in
  let _ := e_print (impl_2__new_v1 ([""%string; "
"%string]) ([impl_1__new_debug (baz)])) in
  let _ := tt in
  tt.
