(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.

(* NotImplementedYet *)

Definition main (_ : unit) : (t_i32*unit) :=
  let is_true := f_eq (f_len (args (tt))) (1) in
  let countdown := 10 in
  (failure ("(FunctionalizeLoops) something is not implemented yet.This is discussed in issue https://github.com/hacspec/hax/issues/933.
Please upvote or comment this issue if you see this error message.
Unhandled loop kind"%string) ("{
 (loop {
 |countdown| {
 (if core::cmp::f_gt(countdown, 0) {
 {
 let a: int = { 100 };
 {
 let b: int = { 100 };
 {
 let Tuple2(a, b): tuple2<int, int> = {
 {
 (for _ in (core::iter::traits::collect..."%string),tt).
